services:
  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:1.10.0
    ports:
      - "8080:8080"
    configs:
      - source: swarm_cd_config
        target: /app/config.yaml
      - source: swarm_cd_repos
        target: /app/repos.yaml
      - source: swarm_cd_stacks
        target: /app/stacks.yaml
    secrets:
      - source: sops_age_key
        target: /secrets/age.key
    environment:
      SOPS_AGE_KEY_FILE: /secrets/age.key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager

configs:
  swarm_cd_config:
    file: ./config.yaml
  swarm_cd_repos:
    file: ./repos.yaml
  swarm_cd_stacks:
    file: ./stacks.yaml

secrets:
  sops_age_key:
    external: true
